export type LocalProviderServiceType =
  | "dog-training"
  | "dog-grooming"
  | "emergency-vet"
  | "dog-friendly"
  | "dog-boarding"
  | "dog-daycare"
  | "dog-walker"
  | "pet-sitter";

export type LocalProviderLinkType = "editorial" | "sponsored" | "ugc";

export type LocalProvider = {
  name: string;
  city: string;
  province: string;
  serviceTypes: LocalProviderServiceType[];
  website?: string;
  phone?: string;
  email?: string;
  areaServed?: string;
  address?: string;
  sourceUrl: string;
  sourceLabel: string;
  lastChecked: string;
  notes: string;
  verificationStatus: "verified-direct" | "verified-source";
  linkType?: LocalProviderLinkType;
};

export const localProviders: LocalProvider[] = [
  {
    name: "DTA Dog Training Academy",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "https://www.dtacademy.co.za/",
    phone: "+27 83 640 7247",
    areaServed: "Durban",
    sourceUrl: "https://www.dtacademy.co.za/",
    sourceLabel: "Official DTA Dog Training Academy website",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog training provider with puppy, obedience, behaviour consultation, and contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Training Durban",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingdurban.co.za/",
    phone: "031 100 1962",
    email: "info@dogtrainingdurban.co.za",
    areaServed: "Durban",
    sourceUrl: "https://www.dogtrainingdurban.co.za/contact/",
    sourceLabel: "Official Dog Training Durban contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog and puppy training provider with phone, email, and contact form listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Smart Dog",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "http://www.thesmartdog.co.za",
    phone: "081 270 4672",
    email: "info@thesmartdog.co.za",
    areaServed: "Durban and surrounding areas",
    sourceUrl:
      "https://www.pethealthcare.co.za/pet-services/animal-training-service/kwazulu-natal/smart-dog-0",
    sourceLabel: "Pet Health Care South Africa listing",
    lastChecked: "2026-06-14",
    notes:
      "Durban-area dog training option with phone, email, and website details listed by Pet Health Care South Africa. Confirm current classes and availability before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Durban Dog School",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "http://www.mk9.co.za",
    phone: "082 321 3648",
    areaServed: "Durban",
    sourceUrl:
      "https://www.pethealthcare.co.za/pet-services/animal-training-service/kwazulu-natal/durban-dog-school",
    sourceLabel: "Pet Health Care South Africa listing",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog training option with phone and website details listed by Pet Health Care South Africa. Ask about class format, vaccination requirements, and training methods.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Training at Your Home",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Sandton, Bryanston, Fourways, Midrand, Johannesburg, and nearby areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider listing Sandton and nearby Gauteng areas on its official website. Confirm service area and behaviour support fit before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "4 Paws K9 Services",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://4pawsk9services.co.za/",
    phone: "079 495 1825",
    email: "4pawsk9sa@gmail.com",
    areaServed: "Sandton and nearby Gauteng areas",
    sourceUrl: "https://4pawsk9services.co.za/",
    sourceLabel: "Official 4 Paws K9 Services website",
    lastChecked: "2026-06-14",
    notes:
      "Dog training service with phone, email, and WhatsApp details listed on its official website. Ask about humane methods, owner involvement, and session structure.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Smart Puppy School Sunninghill Vet",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://puppyschool.co.za/hills-puppy-school/smart-puppy-school-sunninghill-vet/",
    phone: "083 306 4599",
    email: "smartpuppyschool@gmail.com",
    address: "4 Edison Cres, Sunninghill, Sandton, 2157",
    areaServed: "Sunninghill and Sandton",
    sourceUrl: "https://puppyschool.co.za/hills-puppy-school/smart-puppy-school-sunninghill-vet/",
    sourceLabel: "Smart Puppy School Sunninghill Vet listing",
    lastChecked: "2026-06-14",
    notes:
      "Puppy school listing for Sunninghill Vet with address, phone, and email. Check class age ranges, vaccination requirements, and safe socialisation rules.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Training Lonehill",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://dogtraininglonehill.co.za/",
    address: "21B Pine Road, Broadacres AH, Sandton",
    areaServed: "Lonehill, Broadacres, Fourways, and Sandton",
    sourceUrl: "https://dogtraininglonehill.co.za/",
    sourceLabel: "Official Dog Training Lonehill website",
    lastChecked: "2026-06-14",
    notes:
      "Sandton-area dog training venue with its Broadacres address listed on the official website. Confirm current class times and training approach before attending.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Maestro Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.maestrogrooming.co.za/",
    phone: "012 661 0183",
    email: "info@maestrogrooming.co.za",
    address: "73 Panorama Road, Rooihuiskraal, Centurion",
    areaServed: "Centurion",
    sourceUrl: "https://www.maestrogrooming.co.za/",
    sourceLabel: "Official Maestro Grooming website",
    lastChecked: "2026-06-14",
    notes:
      "Centurion grooming parlour with address, phone, mobile grooming contact, and email details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dapper Paws Mobile Pet Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://dapperpaws.co.za/mobile-pet-grooming-services-centurion/",
    phone: "+27 71 746 7949",
    email: "info@dapperpaws.co.za",
    areaServed: "Centurion",
    sourceUrl: "https://dapperpaws.co.za/mobile-pet-grooming-services-centurion/",
    sourceLabel: "Official Dapper Paws Centurion page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with Centurion service page, phone, and email listed on its official website. Confirm water, electricity, and access needs before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Royal R Us Mobile Pet Grooming Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://royalrus.co.za/centurion",
    phone: "081 745 2338",
    email: "admin@royalrusmobilepetgrooming.co.za",
    areaServed: "Centurion",
    sourceUrl: "https://royalrus.co.za/centurion",
    sourceLabel: "Official Royal R Us Centurion page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming service with Centurion page, phone, and email listed on the official Royal R Us website. Confirm current coverage and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mera Grooming Parlour",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://meraparlour.co.za/Contact.html",
    phone: "012 756 1291",
    email: "shop@meraparlour.co.za",
    address: "Hennopsview, Centurion",
    areaServed: "Centurion",
    sourceUrl: "https://meraparlour.co.za/Contact.html",
    sourceLabel: "Official Mera Grooming Parlour contact page",
    lastChecked: "2026-06-14",
    notes:
      "Centurion grooming parlour with contact page listing Hennopsview location, phone numbers, and email. Confirm handling for nervous dogs and matted coats.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Woof & Meow Pet Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://petgrooming.co.za/contact-us/",
    phone: "+27 64 844 4145",
    areaServed: "Centurion",
    sourceUrl: "https://petgrooming.co.za/contact-us/",
    sourceLabel: "Official Woof & Meow contact page",
    lastChecked: "2026-06-14",
    notes:
      "Centurion pet grooming contact page with phone details listed. Ask about coat-type experience, hygiene, tick and flea policy, and collection times.",
    verificationStatus: "verified-direct",
  },
  {
    name: "West Acres Animal Hospital",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://westacresvet.co.za/",
    phone: "082 455 4595",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://westacresvet.co.za/",
    sourceLabel: "Official West Acres Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary hospital with emergency contact details listed on its official website. Phone ahead in urgent cases so the team can prepare.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Van Wijk Street Vet",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://vanwijkstreetvet.co.za/",
    phone: "+27 82 441 7084",
    email: "info@vwsvet.co.za",
    address: "6 Van Wijk Street, Nelspruit, 1201",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://vanwijkstreetvet.co.za/",
    sourceLabel: "Official Van Wijk Street Vet website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary practice with address, email, daytime number, and emergency number listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Nelspruit Animal Hospital",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://www.nelvet.co.za/contact-us/",
    phone: "013 752 8271",
    email: "mail@nelvet.co.za",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://www.nelvet.co.za/contact-us/",
    sourceLabel: "Official Nelspruit Animal Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit animal hospital contact page listing phone, email, and after-hours contact instructions. Call ahead for emergency guidance.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Vets 66",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://thevets.co.za/",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://thevets.co.za/",
    sourceLabel: "Official The Vets 66 website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary practice whose official website mentions after-hours emergencies. Confirm current emergency access and contact route before relying on it.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws & Boots Country Dog Park",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.pawlife.co.za/pet-carers/midrand/paws-and-boots-country-dog-park",
    areaServed: "Midrand and nearby Gauteng areas",
    sourceUrl: "https://www.pawlife.co.za/pet-carers/midrand/paws-and-boots-country-dog-park",
    sourceLabel: "PawLife listing",
    lastChecked: "2026-06-14",
    notes:
      "Midrand dog-park listing found on PawLife. The listing should be checked directly before visiting because dog-friendly access and operating status can change.",
    verificationStatus: "verified-source",
  },
  {
    name: "Paws4Life",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://paws4life.co.za/",
    phone: "+27 72 445 4310",
    email: "paws4lifetraining@gmail.com",
    areaServed: "Durbanville, Paarl, Melkbosstrand, and Cape Town surrounds",
    sourceUrl: "https://paws4life.co.za/",
    sourceLabel: "Official Paws4Life website",
    lastChecked: "2026-06-14",
    notes:
      "Dog training provider with Cape Town-area locations and contact details listed on its official website. Confirm the closest class venue before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Take the Lead Puppy School",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://www.taketheleadpups.com/",
    phone: "082 762 1240",
    email: "taketheleadpups@gmail.com",
    areaServed: "Strand and Cape Town surrounds",
    sourceUrl: "https://www.taketheleadpups.com/",
    sourceLabel: "Official Take the Lead Puppy School website",
    lastChecked: "2026-06-14",
    notes:
      "Puppy school with trainer contact details listed on its official website. Ask about class age ranges and vaccination requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Dynamics",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://www.dogdynamics.co.za/",
    email: "info@dogdynamics.co.za",
    areaServed: "Constantia and Cape Town",
    sourceUrl: "https://www.dogdynamics.co.za/",
    sourceLabel: "Official Dog Dynamics website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog training provider with class and private training information listed on its official website. Confirm course fit directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pampered Paws",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming", "dog-training", "dog-daycare", "dog-walker"],
    website: "https://pamperedpaws.co.za/",
    phone: "+27 21 012 5810",
    email: "claremont@pamperedpaws.co.za",
    address: "20 Imam Haron Road, Claremont, Cape Town, 7708",
    areaServed: "Claremont, Sea Point, Constantiaberg, and Cape Town",
    sourceUrl: "https://pamperedpaws.co.za/",
    sourceLabel: "Official Pampered Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town pet care provider with grooming, daycare, walks, training, addresses, phone numbers, and emails listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "RoadDogs Mobile Pet Grooming",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://roaddogs.co.za/",
    phone: "084 239 4264",
    email: "info.roaddogs@gmail.com",
    areaServed: "Hout Bay and Cape Town",
    sourceUrl: "https://roaddogs.co.za/",
    sourceLabel: "Official RoadDogs website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with Cape Town-area contact details listed on its official website. Confirm service area and booking requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Captain Paws",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://captainpaws.co.za/",
    areaServed: "Cape Town",
    sourceUrl: "https://captainpaws.co.za/",
    sourceLabel: "Official Captain Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider with public service information on its official website. Confirm current contact route and service area before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Posh Pups Mobile Pet Grooming",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://www.facebook.com/petgroomingcapetown/",
    phone: "+27 67 955 7929",
    email: "poshpupsmobile@gmail.com",
    areaServed: "Cape Town",
    sourceUrl: "https://www.facebook.com/petgroomingcapetown/",
    sourceLabel: "Official Posh Pups Facebook page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public contact details listed on its official social page. Confirm appointment terms before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "TAH Rosmead",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://tah.co.za/rosmead/",
    phone: "021 674 0034",
    address: "78 Rosmead Avenue, Kenilworth, Cape Town",
    areaServed: "Cape Town",
    sourceUrl: "https://tah.co.za/rosmead/",
    sourceLabel: "Official TAH Rosmead page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town veterinary hospital with round-the-clock care information on its official page. Phone ahead in emergencies whenever safe.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Panorama Veterinary Clinic",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://panoramavet.co.za/24-hour-patient-care/",
    phone: "021 930 6632",
    address: "1 Uys Krige Drive, Kaapzicht, Cape Town",
    areaServed: "Cape Town",
    sourceUrl: "https://panoramavet.co.za/24-hour-patient-care/",
    sourceLabel: "Official Panorama Veterinary Clinic 24-hour care page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town veterinary clinic with 24-hour patient care information and public contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "TAH Bellville",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://capespca.co.za/services/animal-hospital/",
    phone: "021 919 1191",
    address: "1 Kontiki Avenue, Glen Ive, Cape Town",
    areaServed: "Bellville and Cape Town",
    sourceUrl: "https://capespca.co.za/services/animal-hospital/",
    sourceLabel: "Cape of Good Hope SPCA after-hours treatment page",
    lastChecked: "2026-06-14",
    notes:
      "After-hours Cape Town veterinary contact listed by the Cape of Good Hope SPCA. Confirm emergency access directly before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Vetscape Animal Hospital",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://vetscape.co.za/",
    phone: "061 101 3909",
    address: "La Paris Farm, R301 Jan Van Riebeeck Road, Paarl, 7646",
    areaServed: "Cape Winelands and greater Cape Town region",
    sourceUrl: "https://vetscape.co.za/",
    sourceLabel: "Official Vetscape website",
    lastChecked: "2026-06-14",
    notes:
      "Small animal hospital with public 24-hour emergency contact details on its official website. Confirm travel distance and intake details before departing.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Simon's Restaurant",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website: "https://simons.co.za/pet-friendly-restaurant-cape-town/",
    areaServed: "Constantia, Cape Town",
    sourceUrl: "https://simons.co.za/pet-friendly-restaurant-cape-town/",
    sourceLabel: "Official Simon's pet-friendly restaurant page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town restaurant with public pet-friendly information on its official website. Confirm current dog rules before visiting.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Chardonnay Deli",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website: "https://insideguide.co.za/cape-town/dog-friendly-restaurants/",
    phone: "021 795 0606",
    email: "info@chardonnaydeli.co.za",
    address: "87 Constantia Main Road, Constantia, Cape Town",
    areaServed: "Constantia, Cape Town",
    sourceUrl: "https://insideguide.co.za/cape-town/dog-friendly-restaurants/",
    sourceLabel: "Inside Guide dog-friendly restaurant listing",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog-friendly restaurant listing with public contact details. Confirm current pet rules and seating availability before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Marks Park Dog Club",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.marksparkdogclub.com/",
    areaServed: "Johannesburg",
    sourceUrl: "https://www.marksparkdogclub.com/",
    sourceLabel: "Official Marks Park Dog Club website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog club with class information listed on its official website. Confirm current class schedule and membership requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "McKaynine Training Centre",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.mckaynine.co.za/",
    areaServed: "Johannesburg and nearby Gauteng areas",
    sourceUrl: "https://www.mckaynine.co.za/",
    sourceLabel: "Official McKaynine website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg training provider with puppy, obedience, and behaviour support information listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Training at Your Home Johannesburg",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Johannesburg and nearby Gauteng areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider listing Johannesburg-area services and direct contact details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "FurryFrenz Dog Training",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.furryfrenz.co.za",
    phone: "+27 83 408 1517",
    areaServed: "Johannesburg",
    sourceUrl: "https://www.zoominfo.com/c/furryfrenz-dog-training/461965297",
    sourceLabel: "ZoomInfo public business contact listing",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog training provider with public website and phone details listed in a business contact source. Confirm details directly before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Paws Gone Wild",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawsgonewild.co.za/",
    phone: "063 647 4283",
    email: "info@pawsgonewild.co.za",
    areaServed: "Johannesburg, Midrand, Centurion, Pretoria, and Hartbeespoort",
    sourceUrl: "https://pawsgonewild.co.za/our-services/",
    sourceLabel: "Official Paws Gone Wild services page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with service areas and contact details listed on its official website. Confirm suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Happy Paws Mobile",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://happypawsmobile.co.za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://happypawsmobile.co.za/",
    sourceLabel: "Official Happy Paws Mobile website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg mobile pet grooming provider with public booking information on its official website. Confirm contact route and suburb coverage.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Doggy Do's Groomery",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://doggydos.co.za/",
    areaServed: "Randburg, West Rand, Sandton, Fourways, and Johannesburg surrounds",
    sourceUrl: "https://doggydos.co.za/",
    sourceLabel: "Official Doggy Do's website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider listing Johannesburg-area suburbs on its official website. Confirm current coverage and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pampered Pets Grooming Parlour at Orange Grove Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.orangegrovevet.co.za/grooming/",
    phone: "011 728 3140",
    email: "info@pamperedpetsgrooming.co.za",
    address: "119 Louis Botha Avenue, Orange Grove, Johannesburg",
    areaServed: "Orange Grove and Johannesburg",
    sourceUrl: "https://www.orangegrovevet.co.za/grooming/",
    sourceLabel: "Orange Grove Veterinary Hospital grooming page",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg grooming parlour with booking phone and email listed on the Orange Grove Veterinary Hospital website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "New South Veterinary Centre",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://nsvc.co.za/",
    phone: "011 682 3213",
    areaServed: "Johannesburg South",
    sourceUrl: "https://nsvc.co.za/",
    sourceLabel: "Official New South Veterinary Centre website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg South veterinary centre with 24-hour emergency care information and public phone details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Fourways Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.fourwaysvet.co.za/",
    phone: "011 705 3411",
    areaServed: "Fourways and Johannesburg",
    sourceUrl: "https://www.fourwaysvet.co.za/",
    sourceLabel: "Official Fourways Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg veterinary hospital with 24/7 emergency care information on its official website. Confirm current intake before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Bryanston Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://bryanstonvet.co.za/",
    phone: "011 706 6023",
    areaServed: "Bryanston and Johannesburg",
    sourceUrl: "https://bryanstonvet.co.za/",
    sourceLabel: "Official Bryanston Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg veterinary hospital with 24-hour emergency and referral information on its official website. Phone ahead when possible.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Johannesburg Specialist Veterinary Clinic",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://jsvc.co.za/",
    phone: "083 698 3819",
    areaServed: "Johannesburg",
    sourceUrl: "https://jsvc.co.za/",
    sourceLabel: "Official Johannesburg Specialist Veterinary Clinic website",
    lastChecked: "2026-06-14",
    notes:
      "Specialist veterinary clinic with public emergency after-hours contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "KC Dog School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.kcdogschool.com/",
    phone: "082 454 1750",
    email: "kcdogs@global.co.za",
    areaServed: "Pretoria",
    sourceUrl: "https://www.kcdogschool.com/",
    sourceLabel: "Official KC Dog School website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria dog school with puppy kindergarten and obedience class contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dirty Paws Dog School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://dirtypaws.co.za/",
    phone: "082 551 4143",
    email: "info@dirtypaws.co.za",
    address: "621 View Street, Rietvalleirand, Pretoria",
    areaServed: "Pretoria",
    sourceUrl: "https://dirtypaws.co.za/",
    sourceLabel: "Official Dirty Paws Dog School website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria dog school with address, phone, and email listed on its official website. Confirm class times and suitability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pink Paws Puppy School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://puppyschool.co.za/hills-puppy-school/pink-paws-puppy-school/",
    phone: "072 264 5260",
    email: "natsreynolds79@gmail.com",
    address: "395 Raasblaar Street, Doornpoort, Pretoria",
    areaServed: "Pretoria North and Doornpoort",
    sourceUrl: "https://puppyschool.co.za/hills-puppy-school/pink-paws-puppy-school/",
    sourceLabel: "Pink Paws Puppy School listing",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria puppy school listing with address, email, and contact number. Ask about vaccination requirements and safe socialisation rules.",
    verificationStatus: "verified-source",
  },
  {
    name: "Treat to Train",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training", "dog-walker", "pet-sitter"],
    website: "https://www.treat-to-train.com/in-person-training",
    areaServed: "Pretoria",
    sourceUrl: "https://www.treat-to-train.com/in-person-training",
    sourceLabel: "Official Treat to Train in-person training page",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria training provider with in-person dog training, dog walks, and sitting services described on its official website. Confirm contact details through the site.",
    verificationStatus: "verified-direct",
  },
  {
    name: "PawBuddies",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawbuddies.co.za/",
    phone: "061 446 1614",
    email: "info@pawbuddies.co.za",
    areaServed: "Pretoria Moot, Pretoria East, Pretoria North, and surrounds",
    sourceUrl: "https://pawbuddies.co.za/",
    sourceLabel: "Official PawBuddies website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria grooming provider with service areas, phone, and email listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Just 4 Paws",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.just4paws.co.za/",
    phone: "084 583 0103",
    email: "info@just4paws.co.za",
    areaServed: "Pretoria",
    sourceUrl: "https://www.just4paws.co.za/",
    sourceLabel: "Official Just 4 Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria grooming provider with mobile grooming contact details listed on its official website. Confirm suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws Gone Wild Pretoria",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawsgonewild.co.za/",
    phone: "063 647 4283",
    email: "info@pawsgonewild.co.za",
    areaServed: "Pretoria, Johannesburg, Midrand, Centurion, and Hartbeespoort",
    sourceUrl: "https://pawsgonewild.co.za/our-services/",
    sourceLabel: "Official Paws Gone Wild services page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider listing Pretoria as a service area with public phone and email details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Royal R Us Gauteng",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://royalrus.co.za/",
    email: "grooming@royalrus.co.za",
    areaServed: "Pretoria and Gauteng",
    sourceUrl: "https://royalrus.co.za/",
    sourceLabel: "Official Royal R Us website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public email and Gauteng service information on its official website. Confirm local coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Olympus 24 Hour Animal Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.olympus24hourvet.com/",
    address: "966 Tonetti Street, Pretoria East",
    areaServed: "Pretoria East",
    sourceUrl: "https://www.olympus24hourvet.com/",
    sourceLabel: "Official Olympus 24 Hour Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria East veterinary hospital with 24-hour hospital information on its official website. Confirm emergency intake before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Onderstepoort Veterinary Academic Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.up.ac.za/veterinary-hospital",
    areaServed: "Pretoria and Gauteng",
    sourceUrl: "https://www.up.ac.za/veterinary-hospital",
    sourceLabel: "University of Pretoria Veterinary Hospital page",
    lastChecked: "2026-06-14",
    notes:
      "University veterinary hospital page stating emergency care availability. Confirm referral, intake, and contact requirements before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Val De Grace Vet",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://valdegrace.co.za/",
    phone: "084 404 1119",
    address: "75 Watermeyer Street, Val-De-Grace, Pretoria",
    areaServed: "Pretoria",
    sourceUrl: "https://valdegrace.co.za/",
    sourceLabel: "Official Val De Grace Vet website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria veterinary practice with public emergency contact details listed on its official website. Phone ahead in urgent cases.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Valley Farm Animal Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.valleyfarmvet.co.za/",
    phone: "012 991 3573",
    areaServed: "Pretoria East",
    sourceUrl: "https://www.valleyfarmvet.co.za/",
    sourceLabel: "Official Valley Farm Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria animal hospital with public contact details on its official website. Confirm emergency and after-hours arrangements directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mobi Dog Grooma Durban",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.doggrooma.co.za/",
    phone: "060 312 2210",
    areaServed: "Durban",
    sourceUrl: "https://www.doggrooma.co.za/",
    sourceLabel: "Official Mobi Dog Grooma website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider listing Durban service and public phone details on its official website. Confirm service area and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog-e Style Mobile Dog Grooming",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.facebook.com/DogeStyleMDG/",
    phone: "068 508 0072",
    areaServed: "Durban",
    sourceUrl: "https://www.facebook.com/DogeStyleMDG/",
    sourceLabel: "Official Dog-e Style Facebook page",
    lastChecked: "2026-06-14",
    notes:
      "Durban mobile grooming provider with public phone details listed on its official social page. Confirm current bookings and coverage directly.",
    verificationStatus: "verified-source",
  },
  {
    name: "Ultimate Pet Care",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.ultimatepetcare.co.za/",
    areaServed: "Durban and selected South African service areas",
    sourceUrl: "https://www.ultimatepetcare.co.za/",
    sourceLabel: "Official Ultimate Pet Care website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public service information on its official website. Confirm Durban coverage and contact details before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Pet Stylist Mobile Grooming",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://thepetstylist.co.za/",
    areaServed: "Selected South African service areas",
    sourceUrl: "https://thepetstylist.co.za/",
    sourceLabel: "Official The Pet Stylist website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with public service information on its official website. Confirm current Durban-area coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Ashburne Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.ashburnevet.co.za/",
    phone: "031 562 1037",
    areaServed: "Durban",
    sourceUrl: "https://www.ashburnevet.co.za/",
    sourceLabel: "Official Ashburne Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Durban veterinary hospital with a public 24/7 emergency hotline listed on its official website. Phone ahead in emergencies whenever safe.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Westville Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.westvet.co.za/contactUs",
    phone: "031 267 8000",
    email: "vet@westvet.co.za",
    address: "31 Jan Hofmeyr Road, Westville",
    areaServed: "Durban and Westville",
    sourceUrl: "https://www.westvet.co.za/contactUs",
    sourceLabel: "Official Westville Veterinary Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban-area veterinary hospital with 24/7 emergency information and public contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Rinaldo Riverside Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.riversidevet.net/index.php/contact-us",
    phone: "031 563 6565",
    address: "102 Umhlanga Rocks Drive, Durban North, Durban",
    areaServed: "Durban North",
    sourceUrl: "https://www.riversidevet.net/index.php/contact-us",
    sourceLabel: "Official Riverside Veterinary Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban North veterinary hospital with public contact details and after-hours referral information listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Hillcrest Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://hillcrestvets.co.za/services/",
    areaServed: "Hillcrest and greater Durban / Highway area",
    sourceUrl: "https://hillcrestvets.co.za/services/",
    sourceLabel: "Official Hillcrest Veterinary Hospital services page",
    lastChecked: "2026-06-14",
    notes:
      "Highway-area animal hospital with emergency and 24-hour hospital information on its official website. Confirm intake and travel time before departing.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mug and Mutt Coffee Shop",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/midrand_za/",
    areaServed: "Pretoria / Midrand nearby area",
    sourceUrl: "https://www.bringfido.com/restaurant/city/midrand_za/",
    sourceLabel: "BringFido Midrand dog-friendly restaurant guide",
    lastChecked: "2026-06-14",
    notes:
      "Dog-friendly venue listed in a public Midrand-area guide. Confirm current outdoor seating and dog rules directly with the venue before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Ouma Isie's Tea Garden and Restaurant",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/midrand_za/",
    areaServed: "Centurion / Midrand nearby area",
    sourceUrl: "https://www.bringfido.com/restaurant/city/midrand_za/",
    sourceLabel: "BringFido Midrand dog-friendly restaurant guide",
    lastChecked: "2026-06-14",
    notes:
      "Nearby dog-friendly tea garden listing found in a public Midrand-area guide. Confirm current pet rules before visiting.",
    verificationStatus: "verified-source",
  },
];

export function providerRelFor(linkType: LocalProviderLinkType = "editorial") {
  if (linkType === "sponsored") return "sponsored nofollow noopener noreferrer";
  if (linkType === "ugc") return "ugc nofollow noopener noreferrer";
  return "nofollow noopener noreferrer";
}

export function serviceTypeFromPath(path: string): LocalProviderServiceType | null {
  if (path.includes("/dog-training-")) return "dog-training";
  if (path.includes("/dog-grooming-")) return "dog-grooming";
  if (path.includes("/emergency-vets-") || path.includes("/emergency-vet-")) return "emergency-vet";
  if (path.includes("/dog-friendly-")) return "dog-friendly";
  if (path.includes("/dog-boarding-kennels-")) return "dog-boarding";
  if (path.includes("/dog-daycare-")) return "dog-daycare";
  if (path.includes("/dog-walkers-")) return "dog-walker";
  if (path.includes("/pet-sitters-")) return "pet-sitter";
  return null;
}

export function cityFromLocalPath(path: string) {
  const parts = path.split("/").filter(Boolean);
  if (parts[0] === "local" || parts[0] === "dog-services" || parts[0] === "local-costs") {
    return parts[1] ?? null;
  }
  return null;
}

export function isLocalServicePath(path: string) {
  return (
    path.startsWith("/local/") ||
    path.startsWith("/dog-services/") ||
    path.startsWith("/local-costs/") ||
    path === "/health/find-a-vet-south-africa"
  );
}

export function getProvidersForPath(path: string) {
  const city = cityFromLocalPath(path);
  const serviceType = serviceTypeFromPath(path);

  if (!city || !serviceType) return [];

  return localProviders.filter(
    (provider) => provider.city === city && provider.serviceTypes.includes(serviceType),
  );
}
