export type LocalProviderServiceType =
  | "dog-training"
  | "dog-grooming"
  | "emergency-vet"
  | "dog-friendly"
  | "dog-boarding"
  | "dog-daycare"
  | "dog-walker"
  | "pet-sitter";

export type LocalProviderLinkType = "editorial" | "sponsored" | "ugc";

export type LocalProvider = {
  name: string;
  city: string;
  province: string;
  serviceTypes: LocalProviderServiceType[];
  website?: string;
  phone?: string;
  email?: string;
  areaServed?: string;
  address?: string;
  sourceUrl: string;
  sourceLabel: string;
  lastChecked: string;
  notes: string;
  verificationStatus: "verified-direct" | "verified-source";
  linkType?: LocalProviderLinkType;
};

export const localProviders: LocalProvider[] = [
  {
    name: "DTA Dog Training Academy",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "https://www.dtacademy.co.za/",
    phone: "+27 83 640 7247",
    areaServed: "Durban",
    sourceUrl: "https://www.dtacademy.co.za/",
    sourceLabel: "Official DTA Dog Training Academy website",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog training provider with puppy, obedience, behaviour consultation, and contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Training Durban",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingdurban.co.za/",
    phone: "031 100 1962",
    email: "info@dogtrainingdurban.co.za",
    areaServed: "Durban",
    sourceUrl: "https://www.dogtrainingdurban.co.za/contact/",
    sourceLabel: "Official Dog Training Durban contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog and puppy training provider with phone, email, and contact form listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Smart Dog",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "http://www.thesmartdog.co.za",
    phone: "081 270 4672",
    email: "info@thesmartdog.co.za",
    areaServed: "Durban and surrounding areas",
    sourceUrl:
      "https://www.pethealthcare.co.za/pet-services/animal-training-service/kwazulu-natal/smart-dog-0",
    sourceLabel: "Pet Health Care South Africa listing",
    lastChecked: "2026-06-14",
    notes:
      "Durban-area dog training option with phone, email, and website details listed by Pet Health Care South Africa. Confirm current classes and availability before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Durban Dog School",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-training"],
    website: "http://www.mk9.co.za",
    phone: "082 321 3648",
    areaServed: "Durban",
    sourceUrl:
      "https://www.pethealthcare.co.za/pet-services/animal-training-service/kwazulu-natal/durban-dog-school",
    sourceLabel: "Pet Health Care South Africa listing",
    lastChecked: "2026-06-14",
    notes:
      "Durban dog training option with phone and website details listed by Pet Health Care South Africa. Ask about class format, vaccination requirements, and training methods.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Training at Your Home",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Sandton, Bryanston, Fourways, Midrand, Johannesburg, and nearby areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider listing Sandton and nearby Gauteng areas on its official website. Confirm service area and behaviour support fit before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "4 Paws K9 Services",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://4pawsk9services.co.za/",
    phone: "079 495 1825",
    email: "4pawsk9sa@gmail.com",
    areaServed: "Sandton and nearby Gauteng areas",
    sourceUrl: "https://4pawsk9services.co.za/",
    sourceLabel: "Official 4 Paws K9 Services website",
    lastChecked: "2026-06-14",
    notes:
      "Dog training service with phone, email, and WhatsApp details listed on its official website. Ask about humane methods, owner involvement, and session structure.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Smart Puppy School Sunninghill Vet",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://puppyschool.co.za/hills-puppy-school/smart-puppy-school-sunninghill-vet/",
    phone: "083 306 4599",
    email: "smartpuppyschool@gmail.com",
    address: "4 Edison Cres, Sunninghill, Sandton, 2157",
    areaServed: "Sunninghill and Sandton",
    sourceUrl: "https://puppyschool.co.za/hills-puppy-school/smart-puppy-school-sunninghill-vet/",
    sourceLabel: "Smart Puppy School Sunninghill Vet listing",
    lastChecked: "2026-06-14",
    notes:
      "Puppy school listing for Sunninghill Vet with address, phone, and email. Check class age ranges, vaccination requirements, and safe socialisation rules.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Training Lonehill",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://dogtraininglonehill.co.za/",
    address: "21B Pine Road, Broadacres AH, Sandton",
    areaServed: "Lonehill, Broadacres, Fourways, and Sandton",
    sourceUrl: "https://dogtraininglonehill.co.za/",
    sourceLabel: "Official Dog Training Lonehill website",
    lastChecked: "2026-06-14",
    notes:
      "Sandton-area dog training venue with its Broadacres address listed on the official website. Confirm current class times and training approach before attending.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Maestro Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.maestrogrooming.co.za/",
    phone: "012 661 0183",
    email: "info@maestrogrooming.co.za",
    address: "73 Panorama Road, Rooihuiskraal, Centurion",
    areaServed: "Centurion",
    sourceUrl: "https://www.maestrogrooming.co.za/",
    sourceLabel: "Official Maestro Grooming website",
    lastChecked: "2026-06-14",
    notes:
      "Centurion grooming parlour with address, phone, mobile grooming contact, and email details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dapper Paws Mobile Pet Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://dapperpaws.co.za/mobile-pet-grooming-services-centurion/",
    phone: "+27 71 746 7949",
    email: "info@dapperpaws.co.za",
    areaServed: "Centurion",
    sourceUrl: "https://dapperpaws.co.za/mobile-pet-grooming-services-centurion/",
    sourceLabel: "Official Dapper Paws Centurion page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with Centurion service page, phone, and email listed on its official website. Confirm water, electricity, and access needs before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Royal R Us Mobile Pet Grooming Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://royalrus.co.za/centurion",
    phone: "081 745 2338",
    email: "admin@royalrusmobilepetgrooming.co.za",
    areaServed: "Centurion",
    sourceUrl: "https://royalrus.co.za/centurion",
    sourceLabel: "Official Royal R Us Centurion page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming service with Centurion page, phone, and email listed on the official Royal R Us website. Confirm current coverage and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mera Grooming Parlour",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://meraparlour.co.za/Contact.html",
    phone: "012 756 1291",
    email: "shop@meraparlour.co.za",
    address: "Hennopsview, Centurion",
    areaServed: "Centurion",
    sourceUrl: "https://meraparlour.co.za/Contact.html",
    sourceLabel: "Official Mera Grooming Parlour contact page",
    lastChecked: "2026-06-14",
    notes:
      "Centurion grooming parlour with contact page listing Hennopsview location, phone numbers, and email. Confirm handling for nervous dogs and matted coats.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Woof & Meow Pet Grooming",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://petgrooming.co.za/contact-us/",
    phone: "+27 64 844 4145",
    areaServed: "Centurion",
    sourceUrl: "https://petgrooming.co.za/contact-us/",
    sourceLabel: "Official Woof & Meow contact page",
    lastChecked: "2026-06-14",
    notes:
      "Centurion pet grooming contact page with phone details listed. Ask about coat-type experience, hygiene, tick and flea policy, and collection times.",
    verificationStatus: "verified-direct",
  },
  {
    name: "West Acres Animal Hospital",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://westacresvet.co.za/",
    phone: "082 455 4595",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://westacresvet.co.za/",
    sourceLabel: "Official West Acres Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary hospital with emergency contact details listed on its official website. Phone ahead in urgent cases so the team can prepare.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Van Wijk Street Vet",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://vanwijkstreetvet.co.za/",
    phone: "+27 82 441 7084",
    email: "info@vwsvet.co.za",
    address: "6 Van Wijk Street, Nelspruit, 1201",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://vanwijkstreetvet.co.za/",
    sourceLabel: "Official Van Wijk Street Vet website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary practice with address, email, daytime number, and emergency number listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Nelspruit Animal Hospital",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://www.nelvet.co.za/contact-us/",
    phone: "013 752 8271",
    email: "mail@nelvet.co.za",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://www.nelvet.co.za/contact-us/",
    sourceLabel: "Official Nelspruit Animal Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit animal hospital contact page listing phone, email, and after-hours contact instructions. Call ahead for emergency guidance.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Vets 66",
    city: "nelspruit",
    province: "Mpumalanga",
    serviceTypes: ["emergency-vet"],
    website: "https://thevets.co.za/",
    areaServed: "Nelspruit / Mbombela",
    sourceUrl: "https://thevets.co.za/",
    sourceLabel: "Official The Vets 66 website",
    lastChecked: "2026-06-14",
    notes:
      "Nelspruit veterinary practice whose official website mentions after-hours emergencies. Confirm current emergency access and contact route before relying on it.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws & Boots Country Dog Park",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.pawlife.co.za/pet-carers/midrand/paws-and-boots-country-dog-park",
    areaServed: "Midrand and nearby Gauteng areas",
    sourceUrl: "https://www.pawlife.co.za/pet-carers/midrand/paws-and-boots-country-dog-park",
    sourceLabel: "PawLife listing",
    lastChecked: "2026-06-14",
    notes:
      "Midrand dog-park listing found on PawLife. The listing should be checked directly before visiting because dog-friendly access and operating status can change.",
    verificationStatus: "verified-source",
  },
  {
    name: "Paws4Life",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://paws4life.co.za/",
    phone: "+27 72 445 4310",
    email: "paws4lifetraining@gmail.com",
    areaServed: "Durbanville, Paarl, Melkbosstrand, and Cape Town surrounds",
    sourceUrl: "https://paws4life.co.za/",
    sourceLabel: "Official Paws4Life website",
    lastChecked: "2026-06-14",
    notes:
      "Dog training provider with Cape Town-area locations and contact details listed on its official website. Confirm the closest class venue before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Take the Lead Puppy School",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://www.taketheleadpups.com/",
    phone: "082 762 1240",
    email: "taketheleadpups@gmail.com",
    areaServed: "Strand and Cape Town surrounds",
    sourceUrl: "https://www.taketheleadpups.com/",
    sourceLabel: "Official Take the Lead Puppy School website",
    lastChecked: "2026-06-14",
    notes:
      "Puppy school with trainer contact details listed on its official website. Ask about class age ranges and vaccination requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Dynamics",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-training"],
    website: "https://www.dogdynamics.co.za/",
    email: "info@dogdynamics.co.za",
    areaServed: "Constantia and Cape Town",
    sourceUrl: "https://www.dogdynamics.co.za/",
    sourceLabel: "Official Dog Dynamics website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog training provider with class and private training information listed on its official website. Confirm course fit directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pampered Paws",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming", "dog-training", "dog-daycare", "dog-walker"],
    website: "https://pamperedpaws.co.za/",
    phone: "+27 21 012 5810",
    email: "claremont@pamperedpaws.co.za",
    address: "20 Imam Haron Road, Claremont, Cape Town, 7708",
    areaServed: "Claremont, Sea Point, Constantiaberg, and Cape Town",
    sourceUrl: "https://pamperedpaws.co.za/",
    sourceLabel: "Official Pampered Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town pet care provider with grooming, daycare, walks, training, addresses, phone numbers, and emails listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "RoadDogs Mobile Pet Grooming",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://roaddogs.co.za/",
    phone: "084 239 4264",
    email: "info.roaddogs@gmail.com",
    areaServed: "Hout Bay and Cape Town",
    sourceUrl: "https://roaddogs.co.za/",
    sourceLabel: "Official RoadDogs website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with Cape Town-area contact details listed on its official website. Confirm service area and booking requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Captain Paws",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://captainpaws.co.za/",
    areaServed: "Cape Town",
    sourceUrl: "https://captainpaws.co.za/",
    sourceLabel: "Official Captain Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider with public service information on its official website. Confirm current contact route and service area before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Posh Pups Mobile Pet Grooming",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-grooming"],
    website: "https://www.facebook.com/petgroomingcapetown/",
    phone: "+27 67 955 7929",
    email: "poshpupsmobile@gmail.com",
    areaServed: "Cape Town",
    sourceUrl: "https://www.facebook.com/petgroomingcapetown/",
    sourceLabel: "Official Posh Pups Facebook page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public contact details listed on its official social page. Confirm appointment terms before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "TAH Rosmead",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://tah.co.za/rosmead/",
    phone: "021 674 0034",
    address: "78 Rosmead Avenue, Kenilworth, Cape Town",
    areaServed: "Cape Town",
    sourceUrl: "https://tah.co.za/rosmead/",
    sourceLabel: "Official TAH Rosmead page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town veterinary hospital with round-the-clock care information on its official page. Phone ahead in emergencies whenever safe.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Panorama Veterinary Clinic",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://panoramavet.co.za/24-hour-patient-care/",
    phone: "021 930 6632",
    address: "1 Uys Krige Drive, Kaapzicht, Cape Town",
    areaServed: "Cape Town",
    sourceUrl: "https://panoramavet.co.za/24-hour-patient-care/",
    sourceLabel: "Official Panorama Veterinary Clinic 24-hour care page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town veterinary clinic with 24-hour patient care information and public contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "TAH Bellville",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://capespca.co.za/services/animal-hospital/",
    phone: "021 919 1191",
    address: "1 Kontiki Avenue, Glen Ive, Cape Town",
    areaServed: "Bellville and Cape Town",
    sourceUrl: "https://capespca.co.za/services/animal-hospital/",
    sourceLabel: "Cape of Good Hope SPCA after-hours treatment page",
    lastChecked: "2026-06-14",
    notes:
      "After-hours Cape Town veterinary contact listed by the Cape of Good Hope SPCA. Confirm emergency access directly before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Vetscape Animal Hospital",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://vetscape.co.za/",
    phone: "061 101 3909",
    address: "La Paris Farm, R301 Jan Van Riebeeck Road, Paarl, 7646",
    areaServed: "Cape Winelands and greater Cape Town region",
    sourceUrl: "https://vetscape.co.za/",
    sourceLabel: "Official Vetscape website",
    lastChecked: "2026-06-14",
    notes:
      "Small animal hospital with public 24-hour emergency contact details on its official website. Confirm travel distance and intake details before departing.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Simon's Restaurant",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website: "https://simons.co.za/pet-friendly-restaurant-cape-town/",
    areaServed: "Constantia, Cape Town",
    sourceUrl: "https://simons.co.za/pet-friendly-restaurant-cape-town/",
    sourceLabel: "Official Simon's pet-friendly restaurant page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town restaurant with public pet-friendly information on its official website. Confirm current dog rules before visiting.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Chardonnay Deli",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website: "https://insideguide.co.za/cape-town/dog-friendly-restaurants/",
    phone: "021 795 0606",
    email: "info@chardonnaydeli.co.za",
    address: "87 Constantia Main Road, Constantia, Cape Town",
    areaServed: "Constantia, Cape Town",
    sourceUrl: "https://insideguide.co.za/cape-town/dog-friendly-restaurants/",
    sourceLabel: "Inside Guide dog-friendly restaurant listing",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog-friendly restaurant listing with public contact details. Confirm current pet rules and seating availability before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Marks Park Dog Club",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.marksparkdogclub.com/",
    areaServed: "Johannesburg",
    sourceUrl: "https://www.marksparkdogclub.com/",
    sourceLabel: "Official Marks Park Dog Club website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog club with class information listed on its official website. Confirm current class schedule and membership requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "McKaynine Training Centre",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.mckaynine.co.za/",
    areaServed: "Johannesburg and nearby Gauteng areas",
    sourceUrl: "https://www.mckaynine.co.za/",
    sourceLabel: "Official McKaynine website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg training provider with puppy, obedience, and behaviour support information listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Training at Your Home Johannesburg",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Johannesburg and nearby Gauteng areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider listing Johannesburg-area services and direct contact details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "FurryFrenz Dog Training",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.furryfrenz.co.za",
    phone: "+27 83 408 1517",
    areaServed: "Johannesburg",
    sourceUrl: "https://www.zoominfo.com/c/furryfrenz-dog-training/461965297",
    sourceLabel: "ZoomInfo public business contact listing",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog training provider with public website and phone details listed in a business contact source. Confirm details directly before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Paws Gone Wild",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawsgonewild.co.za/",
    phone: "063 647 4283",
    email: "info@pawsgonewild.co.za",
    areaServed: "Johannesburg, Midrand, Centurion, Pretoria, and Hartbeespoort",
    sourceUrl: "https://pawsgonewild.co.za/our-services/",
    sourceLabel: "Official Paws Gone Wild services page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with service areas and contact details listed on its official website. Confirm suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Happy Paws Mobile",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://happypawsmobile.co.za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://happypawsmobile.co.za/",
    sourceLabel: "Official Happy Paws Mobile website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg mobile pet grooming provider with public booking information on its official website. Confirm contact route and suburb coverage.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Doggy Do's Groomery",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://doggydos.co.za/",
    areaServed: "Randburg, West Rand, Sandton, Fourways, and Johannesburg surrounds",
    sourceUrl: "https://doggydos.co.za/",
    sourceLabel: "Official Doggy Do's website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider listing Johannesburg-area suburbs on its official website. Confirm current coverage and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pampered Pets Grooming Parlour at Orange Grove Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.orangegrovevet.co.za/grooming/",
    phone: "011 728 3140",
    email: "info@pamperedpetsgrooming.co.za",
    address: "119 Louis Botha Avenue, Orange Grove, Johannesburg",
    areaServed: "Orange Grove and Johannesburg",
    sourceUrl: "https://www.orangegrovevet.co.za/grooming/",
    sourceLabel: "Orange Grove Veterinary Hospital grooming page",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg grooming parlour with booking phone and email listed on the Orange Grove Veterinary Hospital website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "New South Veterinary Centre",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://nsvc.co.za/",
    phone: "011 682 3213",
    areaServed: "Johannesburg South",
    sourceUrl: "https://nsvc.co.za/",
    sourceLabel: "Official New South Veterinary Centre website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg South veterinary centre with 24-hour emergency care information and public phone details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Fourways Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.fourwaysvet.co.za/",
    phone: "011 705 3411",
    areaServed: "Fourways and Johannesburg",
    sourceUrl: "https://www.fourwaysvet.co.za/",
    sourceLabel: "Official Fourways Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg veterinary hospital with 24/7 emergency care information on its official website. Confirm current intake before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Bryanston Veterinary Hospital",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://bryanstonvet.co.za/",
    phone: "011 706 6023",
    areaServed: "Bryanston and Johannesburg",
    sourceUrl: "https://bryanstonvet.co.za/",
    sourceLabel: "Official Bryanston Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg veterinary hospital with 24-hour emergency and referral information on its official website. Phone ahead when possible.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Johannesburg Specialist Veterinary Clinic",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://jsvc.co.za/",
    phone: "083 698 3819",
    areaServed: "Johannesburg",
    sourceUrl: "https://jsvc.co.za/",
    sourceLabel: "Official Johannesburg Specialist Veterinary Clinic website",
    lastChecked: "2026-06-14",
    notes:
      "Specialist veterinary clinic with public emergency after-hours contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "KC Dog School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.kcdogschool.com/",
    phone: "082 454 1750",
    email: "kcdogs@global.co.za",
    areaServed: "Pretoria",
    sourceUrl: "https://www.kcdogschool.com/",
    sourceLabel: "Official KC Dog School website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria dog school with puppy kindergarten and obedience class contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dirty Paws Dog School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://dirtypaws.co.za/",
    phone: "082 551 4143",
    email: "info@dirtypaws.co.za",
    address: "621 View Street, Rietvalleirand, Pretoria",
    areaServed: "Pretoria",
    sourceUrl: "https://dirtypaws.co.za/",
    sourceLabel: "Official Dirty Paws Dog School website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria dog school with address, phone, and email listed on its official website. Confirm class times and suitability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pink Paws Puppy School",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://puppyschool.co.za/hills-puppy-school/pink-paws-puppy-school/",
    phone: "072 264 5260",
    email: "natsreynolds79@gmail.com",
    address: "395 Raasblaar Street, Doornpoort, Pretoria",
    areaServed: "Pretoria North and Doornpoort",
    sourceUrl: "https://puppyschool.co.za/hills-puppy-school/pink-paws-puppy-school/",
    sourceLabel: "Pink Paws Puppy School listing",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria puppy school listing with address, email, and contact number. Ask about vaccination requirements and safe socialisation rules.",
    verificationStatus: "verified-source",
  },
  {
    name: "Treat to Train",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-training", "dog-walker", "pet-sitter"],
    website: "https://www.treat-to-train.com/in-person-training",
    areaServed: "Pretoria",
    sourceUrl: "https://www.treat-to-train.com/in-person-training",
    sourceLabel: "Official Treat to Train in-person training page",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria training provider with in-person dog training, dog walks, and sitting services described on its official website. Confirm contact details through the site.",
    verificationStatus: "verified-direct",
  },
  {
    name: "PawBuddies",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawbuddies.co.za/",
    phone: "061 446 1614",
    email: "info@pawbuddies.co.za",
    areaServed: "Pretoria Moot, Pretoria East, Pretoria North, and surrounds",
    sourceUrl: "https://pawbuddies.co.za/",
    sourceLabel: "Official PawBuddies website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria grooming provider with service areas, phone, and email listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Just 4 Paws",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.just4paws.co.za/",
    phone: "084 583 0103",
    email: "info@just4paws.co.za",
    areaServed: "Pretoria",
    sourceUrl: "https://www.just4paws.co.za/",
    sourceLabel: "Official Just 4 Paws website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria grooming provider with mobile grooming contact details listed on its official website. Confirm suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws Gone Wild Pretoria",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawsgonewild.co.za/",
    phone: "063 647 4283",
    email: "info@pawsgonewild.co.za",
    areaServed: "Pretoria, Johannesburg, Midrand, Centurion, and Hartbeespoort",
    sourceUrl: "https://pawsgonewild.co.za/our-services/",
    sourceLabel: "Official Paws Gone Wild services page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider listing Pretoria as a service area with public phone and email details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Royal R Us Gauteng",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://royalrus.co.za/",
    email: "grooming@royalrus.co.za",
    areaServed: "Pretoria and Gauteng",
    sourceUrl: "https://royalrus.co.za/",
    sourceLabel: "Official Royal R Us website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public email and Gauteng service information on its official website. Confirm local coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Olympus 24 Hour Animal Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.olympus24hourvet.com/",
    address: "966 Tonetti Street, Pretoria East",
    areaServed: "Pretoria East",
    sourceUrl: "https://www.olympus24hourvet.com/",
    sourceLabel: "Official Olympus 24 Hour Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria East veterinary hospital with 24-hour hospital information on its official website. Confirm emergency intake before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Onderstepoort Veterinary Academic Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.up.ac.za/veterinary-hospital",
    areaServed: "Pretoria and Gauteng",
    sourceUrl: "https://www.up.ac.za/veterinary-hospital",
    sourceLabel: "University of Pretoria Veterinary Hospital page",
    lastChecked: "2026-06-14",
    notes:
      "University veterinary hospital page stating emergency care availability. Confirm referral, intake, and contact requirements before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Val De Grace Vet",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://valdegrace.co.za/",
    phone: "084 404 1119",
    address: "75 Watermeyer Street, Val-De-Grace, Pretoria",
    areaServed: "Pretoria",
    sourceUrl: "https://valdegrace.co.za/",
    sourceLabel: "Official Val De Grace Vet website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria veterinary practice with public emergency contact details listed on its official website. Phone ahead in urgent cases.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Valley Farm Animal Hospital",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.valleyfarmvet.co.za/",
    phone: "012 991 3573",
    areaServed: "Pretoria East",
    sourceUrl: "https://www.valleyfarmvet.co.za/",
    sourceLabel: "Official Valley Farm Animal Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria animal hospital with public contact details on its official website. Confirm emergency and after-hours arrangements directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mobi Dog Grooma Durban",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.doggrooma.co.za/",
    phone: "060 312 2210",
    areaServed: "Durban",
    sourceUrl: "https://www.doggrooma.co.za/",
    sourceLabel: "Official Mobi Dog Grooma website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider listing Durban service and public phone details on its official website. Confirm service area and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog-e Style Mobile Dog Grooming",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.facebook.com/DogeStyleMDG/",
    phone: "068 508 0072",
    areaServed: "Durban",
    sourceUrl: "https://www.facebook.com/DogeStyleMDG/",
    sourceLabel: "Official Dog-e Style Facebook page",
    lastChecked: "2026-06-14",
    notes:
      "Durban mobile grooming provider with public phone details listed on its official social page. Confirm current bookings and coverage directly.",
    verificationStatus: "verified-source",
  },
  {
    name: "Ultimate Pet Care",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://www.ultimatepetcare.co.za/",
    areaServed: "Durban and selected South African service areas",
    sourceUrl: "https://www.ultimatepetcare.co.za/",
    sourceLabel: "Official Ultimate Pet Care website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public service information on its official website. Confirm Durban coverage and contact details before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Pet Stylist Mobile Grooming",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-grooming"],
    website: "https://thepetstylist.co.za/",
    areaServed: "Selected South African service areas",
    sourceUrl: "https://thepetstylist.co.za/",
    sourceLabel: "Official The Pet Stylist website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile pet grooming provider with public service information on its official website. Confirm current Durban-area coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Ashburne Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.ashburnevet.co.za/",
    phone: "031 562 1037",
    areaServed: "Durban",
    sourceUrl: "https://www.ashburnevet.co.za/",
    sourceLabel: "Official Ashburne Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Durban veterinary hospital with a public 24/7 emergency hotline listed on its official website. Phone ahead in emergencies whenever safe.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Westville Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.westvet.co.za/contactUs",
    phone: "031 267 8000",
    email: "vet@westvet.co.za",
    address: "31 Jan Hofmeyr Road, Westville",
    areaServed: "Durban and Westville",
    sourceUrl: "https://www.westvet.co.za/contactUs",
    sourceLabel: "Official Westville Veterinary Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban-area veterinary hospital with 24/7 emergency information and public contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Rinaldo Riverside Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://www.riversidevet.net/index.php/contact-us",
    phone: "031 563 6565",
    address: "102 Umhlanga Rocks Drive, Durban North, Durban",
    areaServed: "Durban North",
    sourceUrl: "https://www.riversidevet.net/index.php/contact-us",
    sourceLabel: "Official Riverside Veterinary Hospital contact page",
    lastChecked: "2026-06-14",
    notes:
      "Durban North veterinary hospital with public contact details and after-hours referral information listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Hillcrest Veterinary Hospital",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["emergency-vet"],
    website: "https://hillcrestvets.co.za/services/",
    areaServed: "Hillcrest and greater Durban / Highway area",
    sourceUrl: "https://hillcrestvets.co.za/services/",
    sourceLabel: "Official Hillcrest Veterinary Hospital services page",
    lastChecked: "2026-06-14",
    notes:
      "Highway-area animal hospital with emergency and 24-hour hospital information on its official website. Confirm intake and travel time before departing.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Mug and Mutt Coffee Shop",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/midrand_za/",
    areaServed: "Pretoria / Midrand nearby area",
    sourceUrl: "https://www.bringfido.com/restaurant/city/midrand_za/",
    sourceLabel: "BringFido Midrand dog-friendly restaurant guide",
    lastChecked: "2026-06-14",
    notes:
      "Dog-friendly venue listed in a public Midrand-area guide. Confirm current outdoor seating and dog rules directly with the venue before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Ouma Isie's Tea Garden and Restaurant",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/midrand_za/",
    areaServed: "Centurion / Midrand nearby area",
    sourceUrl: "https://www.bringfido.com/restaurant/city/midrand_za/",
    sourceLabel: "BringFido Midrand dog-friendly restaurant guide",
    lastChecked: "2026-06-14",
    notes:
      "Nearby dog-friendly tea garden listing found in a public Midrand-area guide. Confirm current pet rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Mary Puppins",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-walker", "pet-sitter", "dog-boarding"],
    website: "https://marypuppins.co.za/",
    areaServed: "Hout Bay and Cape Town",
    sourceUrl: "https://marypuppins.co.za/",
    sourceLabel: "Official Mary Puppins website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town pet care provider with daycare, walking, sitting, and boarding services listed on its official website. Confirm current availability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Shuttails Canine Solutions",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://shuttails.co.za/",
    phone: "060 910 1111",
    address: "1 Greenfield Road, Diep River, Cape Town, 7945",
    areaServed: "Diep River and Cape Town",
    sourceUrl: "https://shuttails.co.za/",
    sourceLabel: "Official Shuttails website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog walking and pet visit provider with public contact details listed on its official website. Confirm service area before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Boarding Buddies",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://www.boardingbuddies.co.za/",
    phone: "079 713 9403",
    email: "info@boardingbuddies.co.za",
    address: "69 Exmouth Road, Plumstead, Cape Town",
    areaServed: "Plumstead and Cape Town",
    sourceUrl: "https://www.boardingbuddies.co.za/",
    sourceLabel: "Official Boarding Buddies website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town daycare and boarding provider with address, phone, and email listed on its official website. Confirm vaccination requirements before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Dog Walkers Cape Town",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://thedogwalkers.co.za/",
    phone: "+27 72 816 8386",
    email: "info@thedogwalkers.co.za",
    areaServed: "Cape Town",
    sourceUrl: "https://thedogwalkers.co.za/",
    sourceLabel: "Official The Dog Walkers website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog walking and pet sitting provider with public phone and email details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Roadie Pad & Pet",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://roadie.co.za/padandpet/our-stories/",
    phone: "+27 65 953 2066",
    address: "146 Strand Street, Cape Town, 8001",
    areaServed: "Cape Town and Atlantic Seaboard",
    sourceUrl: "https://roadie.co.za/padandpet/our-stories/",
    sourceLabel: "Official Roadie Pad & Pet website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town dog walking and pet sitting provider with public address and phone details listed on its official website. Confirm availability before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Vienna's Village",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://viennasvillage.co.za/contactus/",
    phone: "082 291 1213",
    email: "jayne@viennasvillage.co.za",
    address: "59 Sea Cottage Drive, Noordhoek, Cape Town",
    areaServed: "Noordhoek and Cape Town",
    sourceUrl: "https://viennasvillage.co.za/contactus/",
    sourceLabel: "Official Vienna's Village contact page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town daycare and boarding provider with address, phone, and email listed on its official contact page. Confirm dog size and care requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Waggy Tail",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-boarding", "dog-walker"],
    website: "https://www.waggytail.co.za/contact-us.html",
    phone: "073 217 9142",
    email: "info@waggytail.co.za",
    areaServed: "Cape Town",
    sourceUrl: "https://www.waggytail.co.za/contact-us.html",
    sourceLabel: "Official Waggy Tail contact page",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town daycare, boarding, and dog walk provider with public phone and email details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Collar Club",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://thecollarclub.co.za/",
    phone: "073 575 4765",
    email: "info@thecollarclub.co.za",
    areaServed: "Cape Town",
    sourceUrl: "https://thecollarclub.co.za/",
    sourceLabel: "Official The Collar Club website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town daycare and boarding provider with public phone and email details listed on its official website. Confirm current enrolment requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "PawFect Daycare",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare"],
    website: "https://www.pawfectdaycare.co.za/",
    phone: "078 501 0787",
    email: "daycare@pawfectpups.co.za",
    address: "Milnerton, Cape Town, 7441",
    areaServed: "Sanddrift, Milnerton, and Cape Town",
    sourceUrl: "https://www.pawfectdaycare.co.za/",
    sourceLabel: "Official PawFect Daycare website",
    lastChecked: "2026-06-14",
    notes:
      "Small-breed Cape Town daycare provider with public contact details listed on its official website. Confirm suitability for your dog's size and temperament.",
    verificationStatus: "verified-direct",
  },
  {
    name: "PuppyLove Daycare",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://www.puppylovedaycare.co.za/",
    phone: "+27 76 637 3733",
    email: "info@puppylovedaycare.co.za",
    address: "Spes Bona Road, Durbanville, Cape Town",
    areaServed: "Durbanville and Cape Town",
    sourceUrl: "https://www.puppylovedaycare.co.za/",
    sourceLabel: "Official PuppyLove Daycare website",
    lastChecked: "2026-06-14",
    notes:
      "Cape Town daycare provider with branch, phone, and email details listed on its official website. Confirm assessment and vaccination requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Table Mountain National Park dog walking areas",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website: "https://www.sanparks.org/parks/table-mountain/what-to-do/activities/dog-walking",
    areaServed: "Cape Town",
    sourceUrl: "https://www.sanparks.org/parks/table-mountain/what-to-do/activities/dog-walking",
    sourceLabel: "SANParks Table Mountain dog walking page",
    lastChecked: "2026-06-14",
    notes:
      "Official SANParks page explaining where dog walking is permitted in Table Mountain National Park. Check permit and area rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "City of Cape Town designated dog beach zones",
    city: "cape-town",
    province: "Western Cape",
    serviceTypes: ["dog-friendly"],
    website:
      "https://resource.capetown.gov.za/documentcentre/Documents/Forms%2C%20notices%2C%20tariffs%20and%20lists/Dogs_and_%20Horses_on%20CTBeaches.pdf",
    areaServed: "Cape Town beaches",
    sourceUrl:
      "https://resource.capetown.gov.za/documentcentre/Documents/Forms%2C%20notices%2C%20tariffs%20and%20lists/Dogs_and_%20Horses_on%20CTBeaches.pdf",
    sourceLabel: "City of Cape Town beach dog-zone document",
    lastChecked: "2026-06-14",
    notes:
      "Official City of Cape Town dog-zone document for beaches. Check current municipal rules before taking a dog to any beach.",
    verificationStatus: "verified-source",
  },
  {
    name: "Happy Tails Doggy Daycare",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-daycare"],
    website: "https://www.happytailsdaycare.com/",
    areaServed: "Fourways, Bryanston, and Johannesburg",
    sourceUrl: "https://www.happytailsdaycare.com/",
    sourceLabel: "Official Happy Tails Doggy Daycare website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog daycare provider with Fourways and Bryanston branches listed on its official website. Confirm enrolment requirements directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "JollyWalker",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://jollywalker.co.za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://jollywalker.co.za/",
    sourceLabel: "Official JollyWalker website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg pet services provider with dog walking and pet sitting services listed on its official website. Confirm suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Waggitytails House & Pet Sitting",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://waggitytails.co.za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://waggitytails.co.za/",
    sourceLabel: "Official Waggitytails website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg pet care provider with home visits, overnight stays, and dog walking services listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pawsome Pups",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-daycare", "dog-boarding", "pet-sitter"],
    website: "https://pawsomepupsdoggydaycare.co.za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://pawsomepupsdoggydaycare.co.za/",
    sourceLabel: "Official Pawsome Pups website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg dog daycare provider with daycare, sleepover, and pet sitting services listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Keringa-Petwings",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-boarding"],
    website: "https://keringa.com/",
    areaServed: "Johannesburg and Gauteng",
    sourceUrl: "https://keringa.com/",
    sourceLabel: "Official Keringa-Petwings website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg-area pet services provider with boarding and pet transport information listed on its official website. Confirm booking requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Badham's Fourways Kennels",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-boarding", "pet-sitter"],
    website: "https://www.4wayskennels.co.za/",
    address: "Stone River Boulevard, Fourways, Johannesburg",
    areaServed: "Fourways and Johannesburg",
    sourceUrl: "https://www.4wayskennels.co.za/",
    sourceLabel: "Official Fourways Kennels website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg-area kennel with boarding and pet accommodation services listed on its official website. Confirm vaccination and booking requirements.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Must Love Dogs Hotel",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-boarding", "dog-daycare"],
    website: "https://www.mustlovedogs.co.za/",
    phone: "072 892 7545",
    email: "info@mustlovedogs.co.za",
    address: "17 Howard Avenue, Chartwell, Fourways, Johannesburg",
    areaServed: "Chartwell, Fourways, and Johannesburg",
    sourceUrl: "https://www.mustlovedogs.co.za/",
    sourceLabel: "Official Must Love Dogs website",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg small-dog care provider with address, phone, and email listed on its official website. Confirm dog size suitability before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Team Petsitters Johannesburg",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["pet-sitter"],
    website: "https://www.teampetsitters.co.za/",
    phone: "079 697 2293",
    areaServed: "Johannesburg and Pretoria",
    sourceUrl: "https://www.teampetsitters.co.za/",
    sourceLabel: "Official Team Petsitters website",
    lastChecked: "2026-06-14",
    notes:
      "Pet sitting provider with Johannesburg and Pretoria coverage and public phone details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Brigadoon Kennels",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://brigadoonkennels.co.za/",
    phone: "082 925 5131",
    email: "info@brigadoonkennels.co.za",
    areaServed: "Kyalami and Midrand",
    sourceUrl: "https://brigadoonkennels.co.za/",
    sourceLabel: "Official Brigadoon Kennels website",
    lastChecked: "2026-06-14",
    notes:
      "Midrand-area daycare and boarding provider with public phone and email details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Waggly Tails",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://www.wagglytails.co.za/",
    phone: "072 186 9519",
    email: "info@wagglytails.co.za",
    areaServed: "Pretoria",
    sourceUrl: "https://www.wagglytails.co.za/",
    sourceLabel: "Official Waggly Tails website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria pet and house sitting provider with dog walking services and public contact details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Woof Away",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://woofaway.co.za/",
    areaServed: "Pretoria",
    sourceUrl: "https://woofaway.co.za/",
    sourceLabel: "Official Woof Away website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria pet care provider with dog walking and pet sitting services listed on its official website. Confirm service area before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "The Dog Walker Pretoria East",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["dog-walker"],
    website: "https://dogwalkerpretoriae.wixsite.com/pretoriaeast",
    phone: "062 032 7694",
    email: "dogwalker.pretoriaeast@gmail.com",
    address: "17 Snowdrop Avenue, Newlands, Pretoria",
    areaServed: "Pretoria East",
    sourceUrl: "https://dogwalkerpretoriae.wixsite.com/pretoriaeast",
    sourceLabel: "Official The Dog Walker Pretoria East website",
    lastChecked: "2026-06-14",
    notes:
      "Pretoria East dog walking provider with public phone, email, and address listed on its official website. Confirm current availability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws Inn Pet Sitting",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["pet-sitter"],
    website: "https://sites.google.com/view/pawsin-pet-sitting/home",
    areaServed: "Pretoria East and Centurion",
    sourceUrl: "https://sites.google.com/view/pawsin-pet-sitting/home",
    sourceLabel: "Paws Inn Pet Sitting public website",
    lastChecked: "2026-06-14",
    notes:
      "Pet sitting provider with Pretoria East and Centurion coverage listed on its public website. Confirm contact route and care arrangements before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "GoSit SA",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["pet-sitter"],
    website: "https://gosit.co.za/",
    email: "queries@gosit.co.za",
    areaServed: "Pretoria and South Africa",
    sourceUrl: "https://gosit.co.za/",
    sourceLabel: "Official GoSit SA website",
    lastChecked: "2026-06-14",
    notes:
      "Pet sitting platform with public contact email listed on its official website. Confirm local sitter availability and process before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Team Petsitters Pretoria",
    city: "pretoria",
    province: "Gauteng",
    serviceTypes: ["pet-sitter"],
    website: "https://www.teampetsitters.co.za/",
    phone: "079 697 2293",
    areaServed: "Pretoria and Johannesburg",
    sourceUrl: "https://www.teampetsitters.co.za/",
    sourceLabel: "Official Team Petsitters website",
    lastChecked: "2026-06-14",
    notes:
      "Pet sitting provider with Pretoria and Johannesburg coverage and public phone details listed on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws Gone Wild Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://pawsgonewild.co.za/",
    phone: "063 647 4283",
    email: "info@pawsgonewild.co.za",
    areaServed: "Sandton and nearby Gauteng areas",
    sourceUrl: "https://pawsgonewild.co.za/our-services/",
    sourceLabel: "Official Paws Gone Wild services page",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider listing Johannesburg-area coverage with public phone and email details. Confirm Sandton suburb coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Doggy Do's Groomery Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://doggydos.co.za/",
    areaServed: "Sandton, Fourways, Randburg, and Johannesburg surrounds",
    sourceUrl: "https://doggydos.co.za/",
    sourceLabel: "Official Doggy Do's website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile dog grooming provider listing Sandton and nearby suburbs on its official website. Confirm current coverage before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Happy Paws Mobile Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://happypawsmobile.co.za/",
    areaServed: "Sandton and Johannesburg",
    sourceUrl: "https://happypawsmobile.co.za/",
    sourceLabel: "Official Happy Paws Mobile website",
    lastChecked: "2026-06-14",
    notes:
      "Mobile grooming provider with public booking information on its official website. Confirm Sandton coverage and appointment terms.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pampered Pets Orange Grove",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["dog-grooming"],
    website: "https://www.orangegrovevet.co.za/grooming/",
    phone: "011 728 3140",
    email: "info@pamperedpetsgrooming.co.za",
    areaServed: "Johannesburg and Sandton surrounds",
    sourceUrl: "https://www.orangegrovevet.co.za/grooming/",
    sourceLabel: "Orange Grove Veterinary Hospital grooming page",
    lastChecked: "2026-06-14",
    notes:
      "Johannesburg grooming parlour with public contact details listed by Orange Grove Veterinary Hospital. Confirm travel and booking details.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Bryanston Veterinary Hospital Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://bryanstonvet.co.za/",
    phone: "011 706 6023",
    areaServed: "Bryanston, Sandton, and Johannesburg",
    sourceUrl: "https://bryanstonvet.co.za/",
    sourceLabel: "Official Bryanston Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Sandton-area veterinary hospital with 24-hour emergency and referral information on its official website. Phone ahead when possible.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Fourways Veterinary Hospital Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.fourwaysvet.co.za/",
    phone: "011 705 3411",
    areaServed: "Fourways, Sandton, and Johannesburg",
    sourceUrl: "https://www.fourwaysvet.co.za/",
    sourceLabel: "Official Fourways Veterinary Hospital website",
    lastChecked: "2026-06-14",
    notes:
      "Sandton-area veterinary hospital with 24/7 emergency care information on its official website. Confirm current intake before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Johannesburg Specialist Veterinary Clinic Sandton",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://jsvc.co.za/",
    phone: "083 698 3819",
    areaServed: "Sandton and Johannesburg",
    sourceUrl: "https://jsvc.co.za/",
    sourceLabel: "Official Johannesburg Specialist Veterinary Clinic website",
    lastChecked: "2026-06-14",
    notes:
      "Specialist veterinary clinic with public emergency after-hours contact details listed on its official website. Confirm intake and directions before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog Training at Your Home Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Centurion and nearby Gauteng areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider with Centurion listed in service coverage and direct contact details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "McKaynine Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.mckaynine.co.za/",
    areaServed: "Centurion and Gauteng",
    sourceUrl: "https://www.mckaynine.co.za/",
    sourceLabel: "Official McKaynine website",
    lastChecked: "2026-06-14",
    notes:
      "Gauteng training provider with dog training information listed on its official website. Confirm Centurion service options directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Treat to Train Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-training", "dog-walker", "pet-sitter"],
    website: "https://www.treat-to-train.com/in-person-training",
    areaServed: "Pretoria and Centurion",
    sourceUrl: "https://www.treat-to-train.com/in-person-training",
    sourceLabel: "Official Treat to Train in-person training page",
    lastChecked: "2026-06-14",
    notes:
      "Training and pet care provider with in-person services listed on its official website. Confirm Centurion availability before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Paws Inn Centurion",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["pet-sitter"],
    website: "https://sites.google.com/view/pawsin-pet-sitting/home",
    areaServed: "Pretoria East and Centurion",
    sourceUrl: "https://sites.google.com/view/pawsin-pet-sitting/home",
    sourceLabel: "Paws Inn Pet Sitting public website",
    lastChecked: "2026-06-14",
    notes:
      "Pet sitting provider with Pretoria East and Centurion coverage listed on its public website. Confirm current care arrangements before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Training at Your Home Midrand",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.dogtrainingatyourhome.co.za/",
    phone: "084 332 0400",
    email: "cliff@dogtrainingatyourhome.co.za",
    areaServed: "Midrand and nearby Gauteng areas",
    sourceUrl: "https://www.dogtrainingatyourhome.co.za/",
    sourceLabel: "Official Dog Training at Your Home website",
    lastChecked: "2026-06-14",
    notes:
      "Home dog training provider listing Midrand service coverage and direct contact details on its official website.",
    verificationStatus: "verified-direct",
  },
  {
    name: "McKaynine Midrand",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.mckaynine.co.za/",
    areaServed: "Midrand and Gauteng",
    sourceUrl: "https://www.mckaynine.co.za/",
    sourceLabel: "Official McKaynine website",
    lastChecked: "2026-06-14",
    notes:
      "Gauteng dog training provider with training information listed on its official website. Confirm Midrand service options directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "4 Paws K9 Services Midrand",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://4pawsk9services.co.za/",
    phone: "079 495 1825",
    email: "4pawsk9sa@gmail.com",
    areaServed: "Midrand, Sandton, and nearby Gauteng areas",
    sourceUrl: "https://4pawsk9services.co.za/",
    sourceLabel: "Official 4 Paws K9 Services website",
    lastChecked: "2026-06-14",
    notes:
      "Dog training service with phone, email, and WhatsApp details listed on its official website. Confirm Midrand availability before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Shaggy Chic Private Dog Park",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.instagram.com/shaggy_chic_sa/",
    phone: "+27 82 551 5282",
    address: "80 Salvia Road, Kyalami Agricultural Holdings, Midrand",
    areaServed: "Kyalami and Midrand",
    sourceUrl: "https://www.instagram.com/p/DQUMaJmldfs/",
    sourceLabel: "Official Shaggy Chic Instagram post",
    lastChecked: "2026-06-15",
    notes:
      "Private dog park with public booking contact and location details on its official social profile. Confirm rules and booking availability before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "The Puppy Palace",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-daycare"],
    website: "https://www.facebook.com/thepuppypalacedaycare/",
    phone: "+27 72 992 7751",
    email: "info@thepuppypalace.co.za",
    address: "70 Marie Avenue, Parkmore, Johannesburg",
    areaServed: "Parkmore, Sandton, and Johannesburg",
    sourceUrl: "https://www.facebook.com/thepuppypalacedaycare/",
    sourceLabel: "Official The Puppy Palace Facebook page",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog daycare provider with public phone, email, and address details listed on its official social page. Confirm current enrolment requirements.",
    verificationStatus: "verified-source",
  },
  {
    name: "Club Street Kennels",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "http://www.clubstreetkennels.co.za/",
    phone: "087 004 0366",
    email: "info@clubstreetkennels.co.za",
    address: "119 Club Street, Linksfield, Johannesburg",
    areaServed: "Linksfield and Johannesburg",
    sourceUrl: "http://www.clubstreetkennels.co.za/",
    sourceLabel: "Official Club Street Kennels website",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg daycare and boarding provider with public website, address, phone, and email details. Confirm details directly before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Dog360",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "dog-training"],
    website: "https://dog360.co.za/service/dog-walking/",
    phone: "+27 73 250 7171",
    areaServed: "Johannesburg",
    sourceUrl: "https://dog360.co.za/service/dog-walking/",
    sourceLabel: "Official Dog360 dog walking page",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog walking and training provider with public contact details listed on its official website. Confirm programme fit before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Professional Pet Services Johannesburg",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-walker", "pet-sitter"],
    website: "https://extremeexhibits.wixsite.com/propetservices",
    phone: "083 752 2676",
    areaServed: "Johannesburg",
    sourceUrl: "https://extremeexhibits.wixsite.com/propetservices",
    sourceLabel: "Professional Pet Services public website",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg pet sitting and dog walking provider with public phone details listed on its website. Confirm availability and care process before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "Paw Squad Training Centre",
    city: "centurion",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://www.pawsquad.co.za/",
    phone: "066 206 8059",
    email: "info@pawsquad.co.za",
    areaServed: "Centurion",
    sourceUrl: "https://www.pawsquad.co.za/",
    sourceLabel: "Official Paw Squad Training Centre website",
    lastChecked: "2026-06-15",
    notes:
      "Centurion dog training provider with public phone and email details listed on its official website. Confirm class availability before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "K9 Training Centre",
    city: "midrand",
    province: "Gauteng",
    serviceTypes: ["dog-training"],
    website: "https://k9training.co.za/contact/",
    address: "Caracal Road, Treesbank AH, Midrand, 1682",
    areaServed: "Midrand",
    sourceUrl: "https://k9training.co.za/contact/",
    sourceLabel: "Official K9 Training Centre contact page",
    lastChecked: "2026-06-15",
    notes:
      "Midrand dog training provider with public location details listed on its official contact page. Confirm class options and contact route directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Wendywood Veterinary Hospital",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://wendywoodvet.co.za/contact/",
    areaServed: "Wendywood and Sandton",
    sourceUrl: "https://wendywoodvet.co.za/contact/",
    sourceLabel: "Official Wendywood Veterinary Hospital contact page",
    lastChecked: "2026-06-15",
    notes:
      "Sandton veterinary hospital with after-hours emergency referral numbers listed on its official contact page. Confirm the correct destination before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Parkmore Veterinary Clinic",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.parkmorevet.co.za/",
    phone: "+27 11 883 4746",
    address: "124 11th Street, Parkmore, Sandton",
    areaServed: "Parkmore and Sandton",
    sourceUrl: "https://www.parkmorevet.co.za/",
    sourceLabel: "Official Parkmore Veterinary Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Sandton veterinary contact point with public phone and location details listed on its official website. Confirm emergency availability before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Riverclub Veterinary Clinic",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.riverclubvet.co.za/",
    address: "51 13th Street, Parkmore, Johannesburg",
    areaServed: "River Club, Parkmore, and Sandton",
    sourceUrl: "https://www.riverclubvet.co.za/",
    sourceLabel: "Official Riverclub Veterinary Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Sandton-area veterinary clinic with public location details listed on its official website. Confirm urgent care arrangements before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Animal Emergency Clinic Parklands",
    city: "sandton",
    province: "Gauteng",
    serviceTypes: ["emergency-vet"],
    website: "https://www.aecvet.co.za/",
    phone: "011 788 4748",
    email: "reception@aecvet.co.za",
    address: "24 Newport Road, Parkwood, Johannesburg",
    areaServed: "Sandton, Parkwood, and Johannesburg",
    sourceUrl: "https://www.sava.co.za/find-a-sava-vet/",
    sourceLabel: "South African Veterinary Association vet listing",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg emergency veterinary contact point listed by SAVA with public phone and email details. Confirm intake before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Polokwane Vet Clinic",
    city: "polokwane",
    province: "Limpopo",
    serviceTypes: ["emergency-vet"],
    website: "https://www.polokwanevetclinic.com/",
    phone: "064 504 3754",
    email: "polokwanevetclinic@gmail.com",
    address: "Unit 5, AMNAZ Centre, 54 Compensatie Street, Polokwane, 0699",
    areaServed: "Polokwane",
    sourceUrl: "https://www.polokwanevetclinic.com/",
    sourceLabel: "Official Polokwane Vet Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Polokwane veterinary contact point with public urgent-care contact details listed on its official website. Confirm emergency arrangements before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Pietersburg Dierekliniek",
    city: "polokwane",
    province: "Limpopo",
    serviceTypes: ["emergency-vet"],
    website: "https://pietersburgvet.co.za/",
    phone: "083 631 7134",
    email: "mwpbgvet@mweb.co.za",
    address: "217 Marshall Street, Polokwane, 0699",
    areaServed: "Polokwane",
    sourceUrl: "https://pietersburgvet.co.za/",
    sourceLabel: "Official Pietersburg Dierekliniek website",
    lastChecked: "2026-06-15",
    notes:
      "Polokwane veterinary clinic with public emergency contact details listed on its official website. Confirm after-hours instructions before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Wolkberg Veterinary Clinic",
    city: "polokwane",
    province: "Limpopo",
    serviceTypes: ["emergency-vet"],
    website: "https://www.waze.com/live-map/directions/za/lp/polokwane/wolkberg-veterinary-clinic?to=place.ChIJY8PA-tnZxh4R4uOuQ82im6c",
    phone: "015 291 1381",
    address: "101 Jorissen Street, Sterpark, Polokwane, 0699",
    areaServed: "Polokwane",
    sourceUrl: "https://www.waze.com/live-map/directions/za/lp/polokwane/wolkberg-veterinary-clinic?to=place.ChIJY8PA-tnZxh4R4uOuQ82im6c",
    sourceLabel: "Waze public place listing",
    lastChecked: "2026-06-15",
    notes:
      "Polokwane veterinary contact point with public phone and address details listed in a public map source. Confirm emergency availability before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "East London Veterinary Hospital",
    city: "east-london",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://www.eastlondonvet.co.za/contact",
    phone: "083 255 3469",
    email: "elvetsa@gmail.com",
    address: "13 Vincent Road, Vincent, East London",
    areaServed: "East London",
    sourceUrl: "https://www.eastlondonvet.co.za/contact",
    sourceLabel: "Official East London Veterinary Hospital contact page",
    lastChecked: "2026-06-15",
    notes:
      "East London veterinary hospital with public emergency contact details listed on its official contact page. Phone ahead in urgent cases.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Berea Veterinary Clinic",
    city: "east-london",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://www.facebook.com/p/Berea-Veterinary-Clinic-61555995251111/",
    phone: "+27 76 348 7229",
    email: "bereaveterinaryclinic@gmail.com",
    areaServed: "Berea, Beacon Bay, and East London",
    sourceUrl: "https://www.facebook.com/p/Berea-Veterinary-Clinic-61555995251111/",
    sourceLabel: "Official Berea Veterinary Clinic Facebook page",
    lastChecked: "2026-06-15",
    notes:
      "East London veterinary contact point with public phone and email details listed on its official social page. Confirm urgent-care availability directly.",
    verificationStatus: "verified-source",
  },
  {
    name: "Beacon Bay Veterinary Clinic",
    city: "east-london",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://veterinary.co.za/find-a-vet/beacon-bay-veterinary-clinic/",
    phone: "043 748 2550",
    address: "22 Bonza Bay Road, Beacon Bay, East London, 5205",
    areaServed: "Beacon Bay and East London",
    sourceUrl: "https://veterinary.co.za/find-a-vet/beacon-bay-veterinary-clinic/",
    sourceLabel: "Veterinary.co.za vet listing",
    lastChecked: "2026-06-15",
    notes:
      "East London veterinary contact point with public phone and address details in a veterinary directory source. Confirm emergency arrangements before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "The Snyp Clinic",
    city: "east-london",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://savet.co.za/vet/the-snyp-clinic",
    phone: "+27 64 823 1771",
    email: "bookings@thesnypclinic.co.za",
    areaServed: "Berea and East London",
    sourceUrl: "https://savet.co.za/vet/the-snyp-clinic",
    sourceLabel: "SAVET public vet listing",
    lastChecked: "2026-06-15",
    notes:
      "East London veterinary contact point with public phone and email details in a veterinary source. Confirm urgent-care availability before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Newton Park Animal Hospital",
    city: "gqeberha",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://www.facebook.com/npvethosp/",
    phone: "082 450 8272",
    areaServed: "Gqeberha / Port Elizabeth",
    sourceUrl: "https://www.facebook.com/npvethosp/",
    sourceLabel: "Official Newton Park Animal Hospital Facebook page",
    lastChecked: "2026-06-15",
    notes:
      "Gqeberha veterinary contact point with public emergency contact details listed on its official social page. Confirm intake before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Mount Croix Animal Clinic",
    city: "gqeberha",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://mountcroixvet.co.za/",
    phone: "041 374 3034",
    areaServed: "Gqeberha / Port Elizabeth",
    sourceUrl: "https://mountcroixvet.co.za/",
    sourceLabel: "Official Mount Croix Animal Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Gqeberha veterinary contact point with public phone details listed on its official website. Confirm emergency availability before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Southern Cross Veterinary Clinic",
    city: "gqeberha",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://www.scvc.co.za/contact.html",
    phone: "041 373 4243",
    email: "scvc@corpdial.co.za",
    address: "8 Salisbury Avenue, Mill Park, Gqeberha, 6001",
    areaServed: "Gqeberha / Port Elizabeth",
    sourceUrl: "https://www.scvc.co.za/contact.html",
    sourceLabel: "Official Southern Cross Veterinary Clinic contact page",
    lastChecked: "2026-06-15",
    notes:
      "Gqeberha veterinary contact point with public phone, email, and address details listed on its official contact page. Confirm urgent-care arrangements directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Lorraine Veterinary Clinic",
    city: "gqeberha",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://lorrainevet.co.za/",
    phone: "072 648 0879",
    email: "admin@lorrainevet.co.za",
    address: "178 Circular Drive, Lorraine, Port Elizabeth",
    areaServed: "Gqeberha / Port Elizabeth",
    sourceUrl: "https://lorrainevet.co.za/",
    sourceLabel: "Official Lorraine Veterinary Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Gqeberha veterinary clinic with public emergency number and contact details listed on its official website. Confirm after-hours process before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "9th Avenue Veterinary Clinic",
    city: "gqeberha",
    province: "Eastern Cape",
    serviceTypes: ["emergency-vet"],
    website: "https://www.9thavevet.com/",
    phone: "041 581 4394",
    address: "23 9th Avenue, Walmer, Port Elizabeth, 6070",
    areaServed: "Gqeberha / Port Elizabeth",
    sourceUrl: "https://www.9thavevet.com/",
    sourceLabel: "Official 9th Avenue Veterinary Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Gqeberha veterinary contact point with public phone and address details listed on its official website. Confirm emergency availability before travelling.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Fichardt Park Animal Clinic",
    city: "bloemfontein",
    province: "Free State",
    serviceTypes: ["emergency-vet"],
    website: "https://fichardtparkanimalclinic.yolasite.com/",
    phone: "067 036 3623",
    email: "fhpdierekliniek@gmail.com",
    address: "152 Benade Drive, Fichardt Park, Bloemfontein, 9301",
    areaServed: "Bloemfontein",
    sourceUrl: "https://fichardtparkanimalclinic.yolasite.com/",
    sourceLabel: "Fichardt Park Animal Clinic website",
    lastChecked: "2026-06-15",
    notes:
      "Bloemfontein veterinary clinic with public after-hours and contact details listed on its website. Confirm emergency arrangements before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Vets at Haldon Animal Hospital",
    city: "bloemfontein",
    province: "Free State",
    serviceTypes: ["emergency-vet"],
    website: "https://vetsathaldon.co.za/",
    phone: "051 522 0300",
    email: "vetsathaldon@gmail.com",
    address: "5 Gluckman Avenue, Wilgehof, Bloemfontein",
    areaServed: "Bloemfontein",
    sourceUrl: "https://vetsathaldon.co.za/",
    sourceLabel: "Official Vets at Haldon website",
    lastChecked: "2026-06-15",
    notes:
      "Bloemfontein animal hospital with public phone, email, and location details listed on its official website. Confirm emergency availability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "VetHealth Animal Clinic",
    city: "bloemfontein",
    province: "Free State",
    serviceTypes: ["emergency-vet"],
    website: "https://www.facebook.com/VetHealthAC/",
    phone: "079 528 1079",
    areaServed: "Bloemfontein",
    sourceUrl: "https://www.facebook.com/VetHealthAC/",
    sourceLabel: "Official VetHealth Animal Clinic Facebook page",
    lastChecked: "2026-06-15",
    notes:
      "Bloemfontein veterinary contact point with public emergency contact details listed on its official social page. Confirm current intake before travelling.",
    verificationStatus: "verified-source",
  },
  {
    name: "Durban Dog Hotel",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-boarding", "pet-sitter"],
    website: "https://durbandoghotel.com/",
    phone: "083 650 2594",
    email: "info@durbandoghotel.com",
    areaServed: "Durban",
    sourceUrl: "https://durbandoghotel.com/",
    sourceLabel: "Official Durban Dog Hotel website",
    lastChecked: "2026-06-15",
    notes:
      "Durban dog boarding provider with public phone and email details listed on its official website. Confirm availability and care arrangements before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Durban & Coast SPCA Boarding Kennels",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-boarding"],
    website: "https://spcadbn.org.za/boarding-kennels/",
    phone: "031 579 6545",
    areaServed: "Durban",
    sourceUrl: "https://spcadbn.org.za/boarding-kennels/",
    sourceLabel: "Durban & Coast SPCA boarding kennels page",
    lastChecked: "2026-06-15",
    notes:
      "Durban boarding kennels contact point listed by Durban & Coast SPCA. Confirm booking requirements and vaccination records directly.",
    verificationStatus: "verified-source",
  },
  {
    name: "Doggy Daycare Pinetown",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-daycare", "dog-boarding"],
    website: "https://www.doggy-daycareptn.com/",
    phone: "084 555 7188",
    areaServed: "Pinetown and Durban",
    sourceUrl: "https://www.doggy-daycareptn.com/",
    sourceLabel: "Official Doggy Daycare Pinetown website",
    lastChecked: "2026-06-15",
    notes:
      "Durban-area daycare and boarding provider with public phone details listed on its official website. Confirm current availability directly.",
    verificationStatus: "verified-direct",
  },
  {
    name: "SuperDogz KZN",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-daycare", "dog-training"],
    website: "https://superdogskzn.co.za/",
    phone: "063 096 5017",
    email: "info@superdogskzn.co.za",
    areaServed: "Durban and KwaZulu-Natal",
    sourceUrl: "https://superdogskzn.co.za/",
    sourceLabel: "Official SuperDogz KZN website",
    lastChecked: "2026-06-15",
    notes:
      "KwaZulu-Natal dog daycare and training provider with public phone and email details listed on its official website. Confirm services before booking.",
    verificationStatus: "verified-direct",
  },
  {
    name: "East Coast Pet Sitters",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["pet-sitter", "dog-walker"],
    website: "https://www.facebook.com/ECPetSitters/",
    phone: "066 131 2357",
    email: "admin@ecpetsitters.co.za",
    areaServed: "Durban and surrounding areas",
    sourceUrl: "https://www.facebook.com/ECPetSitters/",
    sourceLabel: "Official East Coast Pet Sitters Facebook page",
    lastChecked: "2026-06-15",
    notes:
      "Durban pet sitting provider with public phone and email details listed on its official social page. Confirm service area and availability before booking.",
    verificationStatus: "verified-source",
  },
  {
    name: "uShaka Beach dog-friendly area",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-friendly"],
    website: "https://spcadbn.org.za/pet-friendly-holidays-in-durban/",
    areaServed: "Durban beachfront",
    sourceUrl: "https://spcadbn.org.za/pet-friendly-holidays-in-durban/",
    sourceLabel: "Durban & Coast SPCA pet-friendly holidays page",
    lastChecked: "2026-06-15",
    notes:
      "Durban dog-friendly beach area mentioned by Durban & Coast SPCA. Confirm current municipal beach rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Treasure Beach dog-friendly area",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-friendly"],
    website: "https://spcadbn.org.za/pet-friendly-holidays-in-durban/",
    areaServed: "Bluff and Durban",
    sourceUrl: "https://spcadbn.org.za/pet-friendly-holidays-in-durban/",
    sourceLabel: "Durban & Coast SPCA pet-friendly holidays page",
    lastChecked: "2026-06-15",
    notes:
      "Durban dog-friendly beach area mentioned by Durban & Coast SPCA. Confirm leash and access rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Surf Riders Cafe",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/durban_za/",
    areaServed: "Durban beachfront",
    sourceUrl: "https://www.bringfido.com/restaurant/city/durban_za/",
    sourceLabel: "BringFido Durban dog-friendly restaurant listing",
    lastChecked: "2026-06-15",
    notes:
      "Durban dog-friendly restaurant listing found in a public pet travel source. Confirm current outdoor seating and dog rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Circus Circus Cafe",
    city: "durban",
    province: "KwaZulu-Natal",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/durban_za/",
    areaServed: "Durban",
    sourceUrl: "https://www.bringfido.com/restaurant/city/durban_za/",
    sourceLabel: "BringFido Durban dog-friendly restaurant listing",
    lastChecked: "2026-06-15",
    notes:
      "Durban dog-friendly restaurant listing found in a public pet travel source. Confirm current dog rules directly before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Walkhaven Dog Park",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-friendly", "dog-boarding"],
    website: "https://walkhaven.co.za/",
    phone: "071 212 9955",
    areaServed: "Muldersdrift and Johannesburg",
    sourceUrl: "https://walkhaven.co.za/",
    sourceLabel: "Official Walkhaven Dog Park website",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg-area dog park with public visitor information and contact details listed on its official website. Confirm current rules before visiting.",
    verificationStatus: "verified-direct",
  },
  {
    name: "Golden Harvest Park",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/destination/city/johannesburg_za/",
    areaServed: "Johannesburg",
    sourceUrl: "https://www.bringfido.com/destination/city/johannesburg_za/",
    sourceLabel: "BringFido Johannesburg dog-friendly destination guide",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog-friendly park listing found in a public pet travel source. Confirm local rules and leash requirements before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Dog Box Grill and Pizza Mutt",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/johannesburg-south-za/",
    areaServed: "Walkhaven and Johannesburg",
    sourceUrl: "https://www.bringfido.com/restaurant/city/johannesburg-south-za/",
    sourceLabel: "BringFido Johannesburg South restaurant listing",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog-friendly restaurant listing found in a public pet travel source. Confirm current seating and access rules before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Moyo Zoo Lake",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://www.bringfido.com/restaurant/city/johannesburg-south-za/",
    areaServed: "Zoo Lake and Johannesburg",
    sourceUrl: "https://www.bringfido.com/restaurant/city/johannesburg-south-za/",
    sourceLabel: "BringFido Johannesburg South restaurant listing",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog-friendly restaurant listing found in a public pet travel source. Confirm outdoor seating and dog rules directly before visiting.",
    verificationStatus: "verified-source",
  },
  {
    name: "Delta Cafe and Don Quixote",
    city: "johannesburg",
    province: "Gauteng",
    serviceTypes: ["dog-friendly"],
    website: "https://whatsoninjoburg.com/15-pet-friendly-venues-in-joburg-and-surrounds/",
    areaServed: "Craighall Park and Johannesburg",
    sourceUrl: "https://whatsoninjoburg.com/15-pet-friendly-venues-in-joburg-and-surrounds/",
    sourceLabel: "What's On in Joburg pet-friendly venues guide",
    lastChecked: "2026-06-15",
    notes:
      "Johannesburg dog-friendly venue listing found in a local events guide. Confirm current dog rules directly before visiting.",
    verificationStatus: "verified-source",
  },
];

export function providerRelFor(linkType: LocalProviderLinkType = "editorial") {
  if (linkType === "sponsored") return "sponsored nofollow noopener noreferrer";
  if (linkType === "ugc") return "ugc nofollow noopener noreferrer";
  return "nofollow noopener noreferrer";
}

export function serviceTypeFromPath(path: string): LocalProviderServiceType | null {
  if (path.includes("/dog-training-")) return "dog-training";
  if (path.includes("/dog-grooming-")) return "dog-grooming";
  if (path.includes("/emergency-vets-") || path.includes("/emergency-vet-")) return "emergency-vet";
  if (path.includes("/dog-friendly-")) return "dog-friendly";
  if (path.includes("/dog-boarding-kennels-")) return "dog-boarding";
  if (path.includes("/dog-daycare-")) return "dog-daycare";
  if (path.includes("/dog-walkers-")) return "dog-walker";
  if (path.includes("/pet-sitters-")) return "pet-sitter";
  return null;
}

export function cityFromLocalPath(path: string) {
  const parts = path.split("/").filter(Boolean);
  if (parts[0] === "local" || parts[0] === "dog-services" || parts[0] === "local-costs") {
    return parts[1] ?? null;
  }
  return null;
}

export function isLocalServicePath(path: string) {
  return (
    path.startsWith("/local/") ||
    path.startsWith("/dog-services/") ||
    path.startsWith("/local-costs/") ||
    path === "/health/find-a-vet-south-africa"
  );
}

export function getProvidersForPath(path: string) {
  const city = cityFromLocalPath(path);
  const serviceType = serviceTypeFromPath(path);

  if (!city || !serviceType) return [];

  return localProviders.filter(
    (provider) => provider.city === city && provider.serviceTypes.includes(serviceType),
  );
}
